openapi: 3.0.1
info:
  version: 1.0.0
  title: Organization subscription API
  description: this API allows you to create and manage organizations and their subscriptions
servers:
  - url: http://localhost:8081
    description: Local server
paths:
  /organizations:
    post:
      operationId: createOrganization
      description: Creates a new organization
      requestBody:
        description: Organization to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrganizationDto"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/OrganizationDto"

components:
  schemas:
    OrganizationDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        login:
          type: string
        mail:
          type: string
      required:
        - name
        - login
        - mail
    ApiError:
      type: object
      properties:
        status:
          type: number
        timestamp:
          type: string
        message:
          type: string
        businessMessage:
          type: string
        debugMessage:
          type: string
        subErrors:
          type: array
          items:
            $ref: "#/components/schemas/ApiValidationError"
      required:
        - status
        - timestamp
    ApiValidationError:
      type: object
      properties:
        object:
          type: string
        field:
          type: string
        rejectedValue:
          type: string
        message:
          type: string
      required:
        - message
