server:
  port: 8081
spring:
  application:
    name: organization-subscription

keycloak:
  base-url: http://localhost:8080
  client-id: organization-management
  client-secret: eQqBbzIMTrEBGolGWIFfFp31BkkKfjoq
