server:
  port: 8081
spring:
  application:
    name: organization-subscription
  datasource:
    url: jdbc:postgresql://localhost:5433/organization_subscription
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migration/db.changelog-master.yml

keycloak:
  base-url: http://localhost:8080
  client-id: organization-management
  client-secret: eQqBbzIMTrEBGolGWIFfFp31BkkKfjoq
